### ISSUE TITLE
Xp system need gain houraly

### ISSUE THREAD

**Issue by recondiscord** [corpnewt/CorpBot.py#4] opened 2017-01-05 13:42 UTC
Need gain xp, not xp reserve in my case xp reserve nit work :/ pliz change this

**Comment by corpnewt** [comment] 2017-01-05 15:05
Can you explain what you mean by "in my case" and "xp reserve not work"?  The system runs as designed on my local instance of the bot.

**Comment by recondiscord** [comment] 2017-01-05 16:08
In my case does not work, because on my first server, it contains 42 users, but only 10 users know how the xp system works, I wanted to ask if it is possible to increment an xp system, per hour but not save that xp , But already self is deposited in the account of the same, without it having to receive the xp of another person, because in my country few speak English fluently and ends up seeing a lot, disagreement about the operation of the bot, and just wanted to know if It was possible to do this, because I am 4 months behind a bot that performs this function, but I never find a functional one, and yours works perfectly and without errors in the code, it is only a request that I have to you if you do not want Imcrement this, but it would be very good if you put yourself

**Comment by corpnewt** [comment] 2017-01-05 16:15
The bot functions the way I wrote it for my tech-based server - so users get xp for helping others.  Because of that, I won't rewrite the function on my main branch - but you could make a few changes to the XP.py file to switch what gets hourly amounts.

See the following block of code where the XPReserve is incremented (lines 20-37 in XP.py):

	async def addXP(self):
		while not self.bot.is_closed:
			await asyncio.sleep(3600) # runs only every 1 hour (3600 seconds)
			print("Adding XP: {}".format(datetime.datetime.now().time().isoformat()))
			for server in self.bot.servers:
				# Iterate through the servers and add them
				xpAmount   = self.settings.getServerStat(server, "HourlyXP")
				onlyOnline = self.settings.getServerStat(server, "RequireOnline")
				for user in server.members:
					bumpXP = False
					if onlyOnline.lower() == "no":
						bumpXP = True
					else:
						if str(user.status).lower() == "online":
							bumpXP = True
							
					if bumpXP:
						self.settings.incrementStat(user, server, "XPReserve", int(xpAmount))

If you change the last line from:

`self.settings.incrementStat(user, server, "XPReserve", int(xpAmount))`

to:

`self.settings.incrementStat(user, server, "XP", int(xpAmount))`

That should effectively accomplish what you want.

Hopefully that helps - if not, please let me know!

**Comment by recondiscord** [comment] 2017-01-05 16:27
I change but
Rank not changing

XP
652
XP Reserve
240
Joined
2016-12-30 08:08 PM
Current Rank
SimplePony
Next Rank
Captain Pony (48 more xp required)

**Comment by recondiscord** [comment] 2017-01-05 16:27
My ranks

Not a Pony? : 0 XP
Ponys : 60 XP
SimplePony : 100 XP
Regular Pony : 200 XP
Recruit Pony : 300 XP
Soldier Pony : 400 XP
Cabo Pony : 500 XP
Sergeant Pony : 600 XP
Captain Pony : 700 XP
Pony Lieutenant : 800 XP
Lieutenant Colonel Pony : 900 XP
Colony Pony : 1000 XP
Major Pony : 1100 XP
General Pony : 1200 XP
Marshal Pony : 1300 XP
Captain of the Pony : 1400 XP
MasterOFPonys : 1500 XP

**Comment by corpnewt** [comment] 2017-01-05 16:32
I think I see the issue - it's not checking roles after adding xp - it just needs an extra line of code.  The final block *should* look like this if my hunch is correct:

	async def addXP(self):
		while not self.bot.is_closed:
			await asyncio.sleep(3600) # runs only every 1 hour (3600 seconds)
			print("Adding XP: {}".format(datetime.datetime.now().time().isoformat()))
			for server in self.bot.servers:
				# Iterate through the servers and add them
				xpAmount   = self.settings.getServerStat(server, "HourlyXP")
				onlyOnline = self.settings.getServerStat(server, "RequireOnline")
				for user in server.members:
					bumpXP = False
					if onlyOnline.lower() == "no":
						bumpXP = True
					else:
						if str(user.status).lower() == "online":
							bumpXP = True
							
					if bumpXP:
						self.settings.incrementStat(user, server, "XP", int(xpAmount))
						await self.checkroles(user, server.default_channel)

I'm not home to actively test that code - but it should work.  If it doesn't, let me know and I'll see if I can help you tweak it.

**Comment by recondiscord** [comment] 2017-01-05 16:42
Ok, i change and i change time for 1 minute i say with work

**Comment by corpnewt** [comment] 2017-01-05 16:43
Does that mean it's all good?  Everything works as it needs to for your server?

**Comment by recondiscord** [comment] 2017-01-05 16:45
Yes, all Xp works :+1:

**Comment by recondiscord** [comment] 2017-01-05 16:45
Thank you :) and its possible disable Youtube cog?

**Comment by corpnewt** [comment] 2017-01-05 16:47
Yep - take a look at the Main.py file (lines 57-61):

    # Examples - there are 2 parts here, Example, and Music
    example = Example.Example(bot)
    music = Example.Music(bot, settings)
    cogList.append(example)
    cogList.append(music)

You can just comment out the `cogList.append(music)` line to disable - so it would look like:

    # Examples - there are 2 parts here, Example, and Music
    example = Example.Example(bot)
    music = Example.Music(bot, settings)
    cogList.append(example)
    # cogList.append(music)

That still loads dependencies and etc from that file - but bypasses the Music class, so the bot won't stream music.

**Comment by recondiscord** [comment] 2017-01-05 16:53
I disabled 10 cogs that in my case, I will not use it and it worked normally, thanks and another question I know I'm annoying you, but is it possible to disable the xp reserve system? , Because as it is not accumulating more ends up being a useless command in the case

**Comment by recondiscord** [comment] 2017-01-05 16:56
![image](https://cloud.githubusercontent.com/assets/24801374/21689290/06e6e790-d357-11e6-82fe-244f61bb0707.png)

all cogs I disable, and bots work normally :+1:

**Comment by corpnewt** [comment] 2017-01-05 16:58
To remove the xp reserve completely, you'd have to pick through the XP.py module and remove functions and references individually, as it's a pretty integral part of my bot's original XP system - it's fairly ingrained.  Feel free to experiment, and let me know if you have more questions along the way - but since the original issue has been resolved, I'm going to close this topic.

Thanks!

**Closed by corpnewt** 2017-01-05 16:58 UTC
