### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by eunola** [corpnewt/CorpBot.py#115] opened 2021-06-01 18:12 UTC
I keep getting this error when I start my bot. I didn't get it before but after turning on intents I do. I deleted the part that says intents but I am still getting the same error

WEBSOCKET | Connection Failure:: Cannot connect to host 127.0.0.1:2333 ssl:default [Connect call failed ('127.0.0.1', 2333)]
Traceback (most recent call last):
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\shaki\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 943, in create_connection
    raise exceptions[0]
  File "C:\Users\shaki\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 930, in create_connection
    await self.sock_connect(sock, address)
  File "C:\Users\shaki\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "C:\Users\shaki\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 2333)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\wavelink\websocket.py", line 76, in _connect
    self._websocket = await self._node.session.ws_connect(uri, headers=self.headers, heartbeat=self._node.heartbeat)
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\client.py", line 763, in _ws_connect
    proxy_headers=proxy_headers,
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "C:\Users\shaki\PycharmProjects\Medusa\venv\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:2333 ssl:default [Connect call failed ('127.0.0.1', 2333)]

now I’m unable to claiming the bot and it won’t go offline

**Comment by eunola** [comment] 2021-06-01 18:25
It's also not loading any new cogs that i add

**Comment by corpnewt** [comment] 2021-06-02 15:31
Looks like wavelink is not connecting to anything successfully - are you running the required Lavalink server?

**Comment by eunola** [comment] 2021-06-02 16:05
How do I find out what lavalink server it needs?

**Comment by corpnewt** [comment] 2021-06-02 16:05
https://github.com/freyacodes/Lavalink

**Comment by eunola** [comment] 2021-06-02 16:30
Im confused on how to get it to connect to connect

**Comment by corpnewt** [comment] 2021-06-02 16:33
If you run the server on the same machine as CorpBot, then it should connect without extra configuration.  If you require more specific or customized settings, though, you can add them to the settings_dict.json file per [this section](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Cogs/Music.py#L24-L30) of the Music.py Cog.

-CorpNewt

**Comment by eunola** [comment] 2021-06-02 16:58
so all i do is put the server that the error is refering to in this spots?

**Comment by corpnewt** [comment] 2021-06-02 17:02
Not sure I understand what you're asking.  `wavelink` is a python module that can interact with a Lavalink server.  You don't appear to have a Lavalink server setup - so wavelink has nothing to connect to, and throws an exception.  If you intend to use the Music Cog, setup a Lavalink server and add the required info for it (if any) in the settings_dict.json file.  If you do not intend to use the Music Cog, remove it from the Cogs folder.  Beyond that, this is not an issue with CorpBot, but with the local environment, so I will close the issue unless there is some other issue that is on CorpBot's end that is brought to light.

-CorpNewt

**Closed as completed by corpnewt** 2021-06-02 17:02 UTC

**Comment by eunola** [comment] 2021-06-02 17:30
will that fix the biot not letting me claim it?

**Comment by corpnewt** [comment] 2021-06-02 17:39
I see no other issues in the output you pasted initially that would imply issues with the settings, so I'm inclined to believe that either it will, or you'll need to provide more information.

-CorpNewt

**Comment by eunola** [comment] 2021-06-02 17:41
I deleted the Music cog and tried claiming the bot but when I go to use one of the commands that require it being claimed it responds that it hasn't been claimed. It won't even let me flush the settings. I've tried everything including typing it

**Comment by corpnewt** [comment] 2021-06-02 17:42
Can you send all of the logging you get when the bot starts?

-CorpNewt

**Comment by eunola** [comment] 2021-06-02 17:44
Starting up 4 shards...
Connecting...
Connected!

Logged n as: 
843908473820938250/Medusa#8516
---------
- 4 of 4 ready...

All shards ready!

Logged in as:
Medusa#8516 (ID: 843908473820938250)

Invite Link:
https://discordapp.com/oauth2/authorize?client_id=843908473820938250&scope=bot&permissions=8

Loading CogManager...
pymongo not installed, preparing to use JSON
pymongo not installed, preparing to use JSON
Connecting to database on localhost:27017...
Connection failed, trying JSON
Since no mongoDB instance was running, I'm reverting back to the Settings.json
deck.json is malformed!  CAH will not work correctly!
Loading brain from standard.brn...done (96827 categories in 3.59 seconds)
Kernel bootstrap completed in 3.59 seconds
Missing IGDB API - skipping
language failed to load!
    Extension 'Cogs.language' raised an error: NameError: name 'languages' is not defined
Loaded 101 of 102 g.
Checking mutes...
Mutes checked - took 0.0 seconds.
Gathering invites...
Starting flush loop - runs every 600 seconds.
Checking reminders...
Reminders checked - took 0.0009903907775878906 seconds.
Checking strikes...
Strikes checked - took 0.0 seconds.
Verifying Temp Roles...
Temp Roles Done - took 0.0 seconds.
Starting XP loop: 13:43:39.994719
Invites gathered - took 0.18700075149536133 seconds.
Flushed to ./Settings-Backup/Backup-2021-06-02 13.43.json!
Settings Backed Up: 2021-06-02 13.43

**Comment by corpnewt** [comment] 2021-06-02 17:46
Nothing there looks like it would prevent settings from saving.  If you run the `claim` command - what does the bot report?  If it reports that it's been claimed by you, can you run the `$flush` command and see what it says?

-CorpNewt

**Comment by eunola** [comment] 2021-06-02 17:52
It says the bot had been claimed then I run the command and it says it hasn’t

**Comment by corpnewt** [comment] 2021-06-02 17:56
I also see there are mentions of Cogs not in my repo:
```
language failed to load!
Extension 'Cogs.language' raised an error: NameError: name 'languages' is not defined
```
If this is an edited instance of the bot - I can't vouch for the code.

-CorpNewt

**Comment by eunola** [comment] 2021-06-02 18:05
I’ll try removing that one.

**Comment by eunola** [comment] 2021-06-02 18:12
I removed it and it still says the same thing

**Comment by corpnewt** [comment] 2021-06-02 18:14
I have no way of knowing what, if anything, else has been changed or modified.  From what I can see, it's not exhibiting signs of issues in the logging - but I don't provide support for modified bots as I'd have to compare everything to ensure integrity.

-CorpNewt

**Comment by eunola** [comment] 2021-06-02 18:16
okay. thank you

**Comment by corpnewt** [comment] 2021-06-02 18:31
Worth mentioning that just now I:

1. Created a new bot in the developer portal (with all privileged intents enabled)
2. Installed the python deps via `Install.bat` (I'm on Windows)
3. Added a Lavalink folder with `Lavalink.jar` + `application.yml` with the defaults from freyacodes repo
4. Added my token and prefix to the `settings_dict.json` file
5. Started the bot up via `StartBot.bat`
6. Added it via the invite link to a server
7. Ran the `!claim` and `!flush` commands

![image](https://user-images.githubusercontent.com/12772521/120533799-bdb9f400-c3a6-11eb-8815-fcfb51fa11f5.png)

There were no issues, and it worked as expected.  I'm betting the issue is with your bot's setup.

-CorpNewt

**Comment by eunola** [comment] 2021-06-02 18:51
Okay I’ll try editing my bot setup again
