### ISSUE TITLE
Settings.py KeyError

### ISSUE THREAD

**Issue by iDutchy** [corpnewt/CorpBot.py#78] opened 2019-05-17 08:18 UTC
Hello,

Somehow, out of nowhere, my bot wont start anymore... Apparently some KeyError? I use the latest updated Settings.py file.

```May 17 04:03:13 dutchy env[29452]: Ignoring exception in on_connect
May 17 04:03:13 dutchy env[29452]: Traceback (most recent call last):
May 17 04:03:13 dutchy env[29452]:   File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 577, in _load_from_module_spec
May 17 04:03:13 dutchy env[29452]:     setup(self)
May 17 04:03:13 dutchy env[29452]:   File "/usr/bin/CharlesBot/cogs/Settings.py", line 25, in setup
May 17 04:03:13 dutchy env[29452]:     bot.add_cog(Settings(bot))
May 17 04:03:13 dutchy env[29452]:   File "/usr/bin/CharlesBot/cogs/Settings.py", line 301, in __init__
May 17 04:03:13 dutchy env[29452]:     self.load_local()
May 17 04:03:13 dutchy env[29452]:   File "/usr/bin/CharlesBot/cogs/Settings.py", line 351, in load_local
May 17 04:03:13 dutchy env[29452]:     self.serverDict["Servers"][collection_name] = collection
May 17 04:03:13 dutchy env[29452]: KeyError: 'Servers'
May 17 04:03:13 dutchy env[29452]: The above exception was the direct cause of the following exception:
May 17 04:03:13 dutchy env[29452]: Traceback (most recent call last):
May 17 04:03:13 dutchy env[29452]:   File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 255, in _run_event
May 17 04:03:13 dutchy env[29452]:     await coro(*args, **kwargs)
May 17 04:03:13 dutchy env[29452]:   File "/usr/bin/CharlesBot/index.py", line 43, in on_connect
May 17 04:03:13 dutchy env[29452]:     bot.load_extension("cogs.Settings")
May 17 04:03:13 dutchy env[29452]:   File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 622, in load_extension
May 17 04:03:13 dutchy env[29452]:     self._load_from_module_spec(lib, name)
May 17 04:03:13 dutchy env[29452]:   File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 581, in _load_from_module_spec
May 17 04:03:13 dutchy env[29452]:     raise errors.ExtensionFailed(key, e) from e
May 17 04:03:13 dutchy env[29452]: discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.Settings' raised an error: KeyError: 'Servers'```

**Comment by corpnewt** [comment] 2019-05-18 01:58
I'll have to look into it - the Settings.py file for the Rewrite branch seems to have some issues currently.  My instance of the bot runs the redis branch so that's been my priority.

-CorpNewt

**Comment by iDutchy** [comment] 2019-05-19 23:09
Thanks. But here comes the weird part...

I use this Settings.py file in 2 of my bots. The files are both exactly the same. Only, just 1 of the 2 bots has this issue...

**Comment by iDutchy** [comment] 2019-05-19 23:46
Update: bot is working again. The issue was the Settings.json file...

What it looked like:
```json
{
  "Servers": {
    "518526509712146453": {
      "_id":
```

What it was supposed to look like:
```json
{
  "token": "",
  "ttslang": "en-au",
  "error_logging": false,
  "debug": false,
  "Owner": [
    171539705043615744
  ],
  "mongodb_migrated": true
}
```

Idk why or how, but I probably did something and messed up... Wouldnt be the first time lmao

**Comment by corpnewt** [comment] 2019-05-20 00:01
Odd - I'll still go through and look at that one of these days, but I'll close this issue for the time being.  Glad it seems to work as intended again.

-CorpNewt

**Closed as completed by corpnewt** 2019-05-20 00:01 UTC

**Comment by skylarr1227** [comment] 2019-09-24 15:39
I have this same issue... Can we look into this or has it been already

**Comment by corpnewt** [comment] 2019-09-24 15:40
@DutchAssassin mentioned that his Settings.json file was malformed.  That would be the first place I would look.

If that looks as it should - you can post the exact error output you get and I can take a look.

-CorpNewt

As an aside - I just cleared my own Settings.json on my test copy of the bot, and started it up - it worked fine.  So running the bot from scratch works as intended.  If you can find out which setting is malformed, and/or when that happened - I can look more into it.  I might need a copy of your Settings.json alongside the error though.

---

Another edit - if you're using the MongoDB implementation, that's never been fully tested or confirmed working.  If you intend to use a db with the bot - look at the [redis](https://github.com/corpnewt/CorpBot.py/tree/redis) branch instead, which is the branch I personally use.

---

*Last edit, I hope:*

I tried running some owner-only commands on the rewrite copy with fresh settings, and it looks as though there was an issue with the "Owner" key on the settingsDict - so I fixed that in [this commit](https://github.com/corpnewt/CorpBot.py/commit/c1b9365d13291bfbfa28ad9b2f683e1b88638720).  Hopefully that fixes whatever issue you had @skylarr1227 - let me know if anything else is amiss after updating.

**Comment by skylarr1227** [comment] 2019-09-24 16:32
That did it thanks!!!

**Comment by corpnewt** [comment] 2019-09-24 16:33
Awesome - glad that worked 👌
